[build]
  functions = "netlify/functions"  # Ceci doit pointer vers le bon dossier des fonctions
  node_version = "14"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200