[build]
  functions = "netlify/functions"  # Ceci doit pointer vers le bon dossier des fonctions
  node_version = "14"  

[[redirects]]
from = "/OneSignalSDKWorker.js"
to = "/OneSignalSDKWorker.js"
status = 200
force = true

[[redirects]]
from = "/OneSignalSDKUpdaterWorker.js"
to = "/OneSignalSDKUpdaterWorker.js"
status = 200
force = true

[[headers]]
for = "/*"
[headers.values]
  Access-Control-Allow-Origin = "*"

[[headers]]
for = "/OneSignalSDKWorker.js"
[headers.values]
  Service-Worker-Allowed = "/"
